### ISSUE TITLE
No messages going to FineCollectionService and VehicleRegistrationService

### ISSUE THREAD

**Issue by nina0901** [EdwinVW/dapr-traffic-control#16]
[FCS.txt](https://github.com/EdwinVW/dapr-traffic-control/files/7620604/FCS.txt)
[TCS.txt](https://github.com/EdwinVW/dapr-traffic-control/files/7620605/TCS.txt)
[VRS.txt](https://github.com/EdwinVW/dapr-traffic-control/files/7620606/VRS.txt)
I was following DaprCon and Traffic application worked until I put Actors.
Now TrafficControl receives msgs fromSimulation but FineCollectionService and VehicleRegistrationService don't.
Tried also 
https://github.com/EdwinVW/dapr-traffic-control

**Comment by EdwinVW** [comment]
Hi @nina0901. Thanks for you interest in the Dapr Traffic Control sample!

I've just changed the topic that is used by the actor to send the speeding-violations (this was a bug!). See 294bfdc. It now uses the `speedingviolations` topic (in stead of the `collectfine` topic). So please pull the latest version.

I've just tested this of Dapr Traffic Control with the Actor implementation (with the fix described above) and it worked as expected. I was not able to reproduce the issue.

So let's dive into the logging you shared. I see in the FCS logging that something went wrong with the subscription to the `speedingviolations` topic by the FCS. A subscription already exists. 

You can try to fix the problem by removing the `speedingviolations` exchange from RabbitMQ. Follow these instructions:

1. Stop all the Dapr Traffic Control services.
2. Open the [RabbitMQ management portal](http://localhost:15672).
3.  Login with username `guest` and password `guest`. 
4. Open the `Exchanges` tab.
5. Select the `speedingviolations` exchange. 
6. Click the `Delete` button on the bottom and confirm the deletion.

You can also delete the `collectfine` topic (if that is present).

Now restart all services in the described order (VRS, FCS, TCS, SIM) and see whether the issue is gone. 

Please let me know the result!
