### ISSUE TITLE
mosquitto image pull policy set to never?

### ISSUE THREAD

**Issue by larryclaman** [EdwinVW/dapr-traffic-control#22]
While trying to get this working on AKS, I noticed that in the mosquitto manifest, you have imagepullpolicy set to 'Never'.
This will prevent the cluster from EVER pulling the image.

https://github.com/EdwinVW/dapr-traffic-control/blob/cd397cdc8f52758c3b5c426b5f43f795433d3168/src/k8s/mosquitto.yaml#L24

**Comment by EdwinVW** [comment]
Hi @larryclaman. Thanks for your interest in this repo!

The reason why the `imagePullPolicy` is set to `Never` is because you need to build the Mosquitto Docker image locally first. This will make sure the correct Mosquitto configuration is used. The default Mosquitto image (when pulled from Docker Hub) does not work out of the box. See [this paragraph](https://github.com/EdwinVW/dapr-traffic-control#run-the-application-on-kubernetes) in the readme.

**Comment by larryclaman** [comment]
hmm, I understand what you're trying to fix, but I would alternatively suggest renaming the custom mosquitto image to something other than 'mosquitto'.  eg, name it (and reference it as) 'ts-mosquitto'.  Then you can get rid of the imagepullpolicy.

FWIW, I am developing a fork of this project that will automate deployment of the application to AKS.  Happy to contribute back if you're interested.

**Comment by EdwinVW** [comment]
To differentiate between the default Mosquitto image and the local one, I've added `dapr-trafficcontrol` as repository (see the [Mosquitto K8S manifest file](https://github.com/EdwinVW/dapr-traffic-control/blob/cd397cdc8f52758c3b5c426b5f43f795433d3168/src/k8s/mosquitto.yaml#L23)). Because this repo does not exist, I've added the imagePullPolicy. 

For an AKS implementation, you could indeed bake your own Mosquitto image (including the config) and put it in an ACR.

**Comment by larryclaman** [comment]
Hi Edwin,
I looked into this a little more (as I continue to develop my AKS-ready version of this project) and I'm curious as to why you are creating your own local mosquitto image.  Looking at the Dockerfile, it uses the vanilla mosquitto image, but simply bakes in the conf file:
```Dockerfile
FROM eclipse-mosquitto:latest

# override default config-file
COPY ./mosquitto.conf /mosquitto/config/mosquitto.conf
```
Curious as to why you chose this route (using a custom image)?  eg, why not simply pass the conf file as a mounted volume (per the instructions [here](https://hub.docker.com/_/eclipse-mosquitto/)) as `docker run -it -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto`
And for a K8S deployment, you can achieve the same thing by passing the conf file as a configmap.

**Comment by EdwinVW** [comment]
Hi Larry. Yes that's also a possibility. But I want to keep it as simple as possible, because the focus of this sample is to learn Dapr. With the custom container image with the config baked-in, users of the sample can use this image in self-hosted mode as well as in K8S. They don't have to switch between specifying a volume mount in self hosted mode and using a K8S config-map when running in K8S. I also don't have to explain this in the instructions and (maybe) confuse people. This is also the reason I don't include a version running on AKS (or Azure Container Apps or ...) in the sample. Those other ways of hosting the sample are cool to have. But the focus should stay on learning Dapr. I hope you understand my considerations in this area.
