### ISSUE TITLE
Maildev container ports not mapped properly

### ISSUE THREAD

**Issue by RasmusSlothJensen** [EdwinVW/dapr-traffic-control#24]
When running the environment locally on windows the maildev container's ports are not mapped properly. I resolved the issue by changing the port mapping in the start-maildev.ps1 file to
```
docker run -d -p 4000:1080 -p 4025:1025 --name dtc-maildev maildev/maildev:latest
```

**To Reproduce**
1. Pull the latest maildev/maildev image
2. Run start-maildev.ps1
3. Open http://localhost:4000

**Expected behavior**
Expected the web app to be displayed in the browser.

**Screenshots**

**Environment (please share as much info as possible):**
 - Windows 11
 - Latest
- localhost

**Additional context**

**Comment by EdwinVW** [comment]
Hi @RasmusSlothJensen. Thanks for your interest in this sample app!

I use an older version of maildev (1.1.0) because the latest version has some issues with rendering the HTML email content. If you pull the latest version of the repo and use the `start-all.ps1` script in the `src/Infrastructure` folder, it should work as expected.

**Comment by RasmusSlothJensen** [comment]
Hi @EdwinVW. I really like the sample app. 

Thank you for the quick response

**Comment by EdwinVW** [comment]
I just checked the MailDev releases and saw that there is a new version (2.0.5). In this version the HTML view is fixed and renders the email correctly. I've updated the manifest files. Please pull again and try it.
